import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Ban, CheckCircle2, ChevronDown, Edit2, Phone, ShieldAlert, ShieldCheck, StickyNote, UserPlus, X } from 'lucide-react';
import { CallLogItem, CallClassification, TruecallerDirectoryProfile } from '../types';

interface CallerDetailModalProps {
  call: CallLogItem | null; calls?: CallLogItem[]; profile?: TruecallerDirectoryProfile | null; isOpen: boolean; onClose:()=>void;
  onBlockNumber:(number:string,label:string)=>void; onMarkSafe:(number:string,name:string)=>void; onOpenReportModal:(number:string)=>void;
  onOpenDisputeModal:(number:string,name:string)=>void; onUpdateCallerName?:(number:string,newName:string)=>void;
  onOpenSmartBlock?:(number:string,pattern:string)=>void; onInitiateCall?:(number:string,name?:string)=>void; onSaveNote?:(callId:string,note:string)=>void;
}
const normalize=(v:string)=>v.replace(/\D/g,'').replace(/^0+/,'');
const duration=(s:number)=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
export default function CallerDetailModal({call,calls=[],profile,isOpen,onClose,onBlockNumber,onMarkSafe,onOpenReportModal,onOpenDisputeModal,onUpdateCallerName,onOpenSmartBlock,onInitiateCall,onSaveNote}:CallerDetailModalProps){
 const [expanded,setExpanded]=useState(true),[editing,setEditing]=useState(false),[name,setName]=useState(''),[note,setNote]=useState('');
 useEffect(()=>{if(isOpen){setExpanded(true);setEditing(false);setName(call?.callerName||profile?.name||'');setNote(call?.notes||'')}},[isOpen,call,profile]);
 const number=call?.number||profile?.number||'', key=normalize(number);
 const history=useMemo(()=>calls.filter(c=>normalize(c.number)===key).sort((a,b)=>b.timestamp-a.timestamp),[calls,key]);
 if(!isOpen||(!call&&!profile))return null;
 const entries=history.length?history:(call?[call]:[]);
 const spamEvidence=entries.filter(c=>c.isSpam||c.classification==='SPAM'||c.classification==='SCAM'||c.riskScore>=60);
 const classification:CallClassification=spamEvidence.some(c=>c.classification==='SCAM')||profile?.riskLevel==='HIGH_RISK'?'SCAM':spamEvidence.length?'SPAM':call?.classification||(profile?.isVerified?'VERIFIED':profile?.isSpam?'SPAM':'UNKNOWN');
 const risk=Math.max(call?.riskScore||0,profile?.spamScore||0,...entries.map(c=>c.riskScore||0));
 const isSpam=classification==='SPAM'||classification==='SCAM'||spamEvidence.length>0||!!profile?.isSpam;
 const isVerified=classification==='VERIFIED'||entries.some(c=>c.isVerifiedBusiness)||!!profile?.isVerified;
 const label=classification==='SCAM'?'High scam risk':classification==='SPAM'?'Spam caller':classification==='SUSPICIOUS'?'Suspicious caller':isVerified?'Verified caller':'Unknown caller';
 const saveNote=()=>{if(call&&onSaveNote)onSaveNote(call.id,note.trim())};
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-0 sm:p-4" role="dialog" aria-modal="true">
  <section className="flex h-full w-full max-w-2xl flex-col overflow-hidden bg-[#0b1016] sm:h-auto sm:max-h-[92vh] sm:rounded-[28px] sm:border sm:border-slate-700 sm:shadow-2xl">
   <header className={`border-b px-5 py-5 ${isSpam?'border-rose-900/60 bg-rose-950/20':'border-slate-800 bg-slate-900/80'}`}>
    <div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-[11px] font-bold ${isSpam?'bg-rose-500/15 text-rose-300':isVerified?'bg-emerald-500/15 text-emerald-300':'bg-slate-800 text-slate-300'}`}>{isSpam?'⚠ ':''}{label}</span><span className="text-[11px] text-slate-500">{entries.length} {entries.length===1?'call':'calls'}</span></div>
     {editing?<div className="flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} className="min-w-0 rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 font-semibold text-white outline-none" autoFocus/><button onClick={()=>{if(name.trim()&&onUpdateCallerName)onUpdateCallerName(number,name.trim());setEditing(false)}} className="rounded-xl bg-blue-600 p-2 text-white"><CheckCircle2 className="h-4 w-4"/></button></div>:<div className="flex items-center gap-2"><h2 className="truncate text-2xl font-bold text-white">{name||'Unknown caller'}</h2>{onUpdateCallerName&&<button onClick={()=>setEditing(true)} className="rounded-lg p-1 text-slate-500 hover:text-white"><Edit2 className="h-4 w-4"/></button>}</div>}
     <p className="mt-1 font-mono text-sm text-slate-400">{number}</p></div><button onClick={onClose} className="rounded-full p-2 text-slate-400 hover:bg-slate-800 hover:text-white"><X className="h-5 w-5"/></button></div>
    {isSpam&&<div className="mt-4 flex gap-3 rounded-2xl border border-rose-800/60 bg-rose-950/40 p-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-rose-400"/><div><div className="text-sm font-semibold text-rose-200">Spam signals detected</div><div className="mt-1 text-xs leading-5 text-rose-300/80">{call?.spamReason||profile?.spamReason||'This caller has protection signals. Unknown callers are not treated as safe.'}</div><div className="mt-1 text-xs text-rose-300">{profile?.spamReportsCount||call?.reportsCount||0} reports · {risk}% risk</div></div></div>}
   </header>
   <div className="flex-1 space-y-4 overflow-y-auto p-5">
    <div className="grid grid-cols-2 gap-2"><button onClick={()=>onInitiateCall?.(number,name)} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-emerald-600 font-semibold text-white"><Phone className="h-4 w-4"/>Call</button><button onClick={()=>onBlockNumber(number,name)} className="flex h-11 items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-900 font-semibold text-slate-200"><Ban className="h-4 w-4"/>Block</button></div>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/80"><button onClick={()=>setExpanded(v=>!v)} className="flex w-full items-center justify-between px-4 py-3 text-left"><div><div className="text-sm font-bold text-white">Call history</div><div className="text-xs text-slate-500">Complete timeline for this number</div></div><ChevronDown className={`h-4 w-4 text-slate-500 ${expanded?'rotate-180':''}`}/></button>{expanded&&<div className="border-t border-slate-800">{entries.map(item=><div key={item.id} className="border-b border-slate-800/80 px-4 py-3 last:border-0"><div className="flex items-center justify-between gap-3"><div><div className={`text-xs font-bold ${item.type==='MISSED'||item.type==='BLOCKED_CANCELLED'?'text-rose-300':'text-slate-200'}`}>{item.type==='MISSED'?'Missed':item.type==='BLOCKED_CANCELLED'?'Blocked':item.type==='INCOMING'?'Incoming':'Outgoing'}</div><div className="mt-1 text-xs text-slate-500">{new Date(item.timestamp).toLocaleString()}</div></div><span className="text-xs text-slate-400">{duration(item.durationSeconds||0)}</span></div>{item.recordingUri&&<div className="mt-2 rounded-xl border border-slate-800 bg-slate-950 p-2"><div className="mb-1 text-xs font-semibold text-slate-300">🔊 Recording</div><audio controls preload="metadata" src={item.recordingUri} className="h-9 w-full"/></div>}{item.notes&&<div className="mt-2 flex gap-2 rounded-xl bg-amber-500/5 p-2 text-xs text-slate-300"><StickyNote className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-400"/>{item.notes}</div>}</div>)}</div>}</section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4"><div className="flex items-center gap-2 text-sm font-bold text-white"><StickyNote className="h-4 w-4 text-amber-400"/>Caller note</div><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="Write a private note about this caller…" className="mt-3 w-full resize-none rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm text-white outline-none placeholder-slate-600"/><button onClick={saveNote} disabled={!call||!onSaveNote} className="mt-2 rounded-xl bg-amber-500 px-4 py-2 text-xs font-bold text-slate-950 disabled:opacity-40">Save note</button></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-950 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-slate-200">{isSpam?<ShieldAlert className="h-4 w-4 text-rose-400"/>:<ShieldCheck className="h-4 w-4 text-blue-400"/>}Protection details</div><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><span className="text-slate-500">Status</span><div className={`mt-1 font-semibold ${isSpam?'text-rose-300':isVerified?'text-emerald-300':'text-slate-300'}`}>{label}</div></div><div><span className="text-slate-500">Risk</span><div className="mt-1 font-semibold text-slate-200">{risk}%</div></div><div><span className="text-slate-500">Calls</span><div className="mt-1 font-semibold text-slate-200">{entries.length}</div></div><div><span className="text-slate-500">Reports</span><div className="mt-1 font-semibold text-slate-200">{profile?.spamReportsCount||Math.max(...entries.map(x=>x.reportsCount||0),0)}</div></div></div></section>
    <div className="flex flex-wrap gap-2">{isSpam&&<button onClick={()=>onMarkSafe(number,name)} className="rounded-xl border border-emerald-900 bg-emerald-500/10 px-3 py-2 text-xs font-semibold text-emerald-300">Not spam</button>}<button onClick={()=>onOpenReportModal(number)} className="rounded-xl border border-slate-800 px-3 py-2 text-xs font-semibold text-slate-300">Report spam</button><button onClick={()=>onOpenDisputeModal(number,name)} className="rounded-xl border border-slate-800 px-3 py-2 text-xs font-semibold text-slate-300">Dispute</button>{onOpenSmartBlock&&<button onClick={()=>onOpenSmartBlock(number,number.slice(0,5))} className="rounded-xl border border-slate-800 px-3 py-2 text-xs font-semibold text-slate-300">Smart block</button>}{onInitiateCall&&<button onClick={()=>onInitiateCall(number,name)} className="inline-flex items-center gap-1 rounded-xl border border-slate-800 px-3 py-2 text-xs font-semibold text-slate-300"><UserPlus className="h-3.5 w-3.5"/>Save / contact</button>}</div>
   </div>
  </section>
 </div>;
}
