import { FormEvent, useMemo, useState } from 'react';
import { Building2, Edit2, Phone, Plus, Search, ShieldCheck, Star, Trash2, UserRound, X } from 'lucide-react';
import { ContactItem, CallLogItem } from '../types';
import { telecomBridge } from '../services/telephony/telecomBridge';

interface ContactsTabProps { contacts:ContactItem[]; onInitiateCall:(number:string,name?:string)=>void; onAddContact:(contact:Omit<ContactItem,'id'>)=>void; onUpdateContact:(id:string,updates:Partial<ContactItem>)=>void; onDeleteContact:(id:string)=>void; onToggleFavorite:(id:string)=>void; recentCalls:CallLogItem[]; }
type CategoryFilter='ALL'|'FAVORITES'|'FAMILY'|'WORK'|'BUSINESSES'|'RECENT';
const clean=(v:string)=>v.replace(/\D/g,'');

export default function ContactsTab({contacts,onInitiateCall,onAddContact,onUpdateContact,onDeleteContact,onToggleFavorite}:ContactsTabProps){
 const [query,setQuery]=useState(''); const [filter,setFilter]=useState<CategoryFilter>('ALL'); const [selected,setSelected]=useState<ContactItem|null>(null); const [editing,setEditing]=useState(false); const [showAdd,setShowAdd]=useState(false); const [name,setName]=useState(''); const [number,setNumber]=useState(''); const [category,setCategory]=useState<ContactItem['category']>('GENERAL');
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase(),d=clean(query);return contacts.filter(c=>{if(filter==='FAVORITES'&&!c.isFavorite)return false;if(filter==='FAMILY'&&c.category!=='FAMILY')return false;if(filter==='WORK'&&c.category!=='WORK')return false;if(filter==='BUSINESSES'&&c.category!=='BUSINESS')return false;if(filter==='RECENT'&&(!c.lastCallTimestamp||c.lastCallTimestamp<Date.now()-604800000))return false;if(!q)return true;return c.name.toLowerCase().includes(q)||Boolean(c.businessCategory?.toLowerCase().includes(q))||(d.length>0&&clean(c.number).includes(d))}).sort((a,b)=>Number(Boolean(b.isFavorite))-Number(Boolean(a.isFavorite))||a.name.localeCompare(b.name))},[contacts,query,filter]);
 const importDevice=()=>{if(!telecomBridge.isAndroidEnvironment())return;telecomBridge.fetchDeviceContacts(1000).forEach(c=>onAddContact({name:c.name,number:c.number,category:'GENERAL',trusted:true,isFavorite:c.isFavorite,notes:'Android Contacts'}))};
 const openEdit=(c:ContactItem)=>{setSelected(c);setName(c.name);setNumber(c.number);setCategory(c.category);setEditing(true)};
 const submit=(e:FormEvent)=>{e.preventDefault();if(!name.trim()||!number.trim())return;if(editing&&selected)onUpdateContact(selected.id,{name:name.trim(),number:number.trim(),category});else onAddContact({name:name.trim(),number:number.trim(),category,trusted:true,isFavorite:category==='FAVORITE',notes:''});setName('');setNumber('');setCategory('GENERAL');setEditing(false);setShowAdd(false);setSelected(null)};
 return <div className="mx-auto w-full max-w-3xl px-4 pb-8 pt-5 sm:px-6">
  <header className="mb-5 flex items-end justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-500">People</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-white">Contacts</h1><p className="mt-1 text-sm text-slate-500">Your people, favorites and verified businesses.</p></div><div className="flex gap-2"><button onClick={importDevice} className="hidden rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-bold text-slate-300 sm:block">Import</button><button onClick={()=>{setName('');setNumber('');setCategory('GENERAL');setShowAdd(true)}} className="flex items-center gap-1.5 rounded-xl bg-white px-3.5 py-2.5 text-xs font-bold text-[#0a0f14]"><Plus className="h-4 w-4"/>Add</button></div></header>
  <div className="relative mb-3"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search contacts" className="h-12 w-full rounded-2xl border border-white/10 bg-[#10161d] pl-10 pr-10 text-sm text-white outline-none placeholder:text-slate-600"/>{query&&<button onClick={()=>setQuery('')} className="absolute right-3 top-1/2 -translate-y-1/2"><X className="h-4 w-4 text-slate-500"/></button>}</div>
  <div className="mb-5 flex gap-2 overflow-x-auto pb-1">{(['ALL','FAVORITES','FAMILY','WORK','BUSINESSES','RECENT'] as CategoryFilter[]).map(v=><button key={v} onClick={()=>setFilter(v)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold ${filter===v?'bg-white text-[#0a0f14]':'bg-white/5 text-slate-400'}`}>{v==='ALL'?'All':v==='FAVORITES'?'Favorites':v==='BUSINESSES'?'Businesses':v[0]+v.slice(1).toLowerCase()}</button>)}</div>
  {filtered.length===0?<div className="rounded-[28px] border border-white/10 bg-[#10161d] p-12 text-center"><UserRound className="mx-auto h-9 w-9 text-slate-700"/><p className="mt-3 text-sm font-semibold text-slate-300">{contacts.length?'No matching contacts':'No contacts yet'}</p><p className="mt-1 text-xs text-slate-600">Add a contact or import your Android address book.</p></div>:<div className="overflow-hidden rounded-[26px] border border-white/10 bg-[#10161d]">{filtered.map(c=><div key={c.id} className="flex items-center gap-3 border-b border-white/5 px-3.5 py-3.5 last:border-0"><button onClick={()=>setSelected(c)} className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-gradient-to-br from-slate-700 to-slate-800 text-sm font-bold text-white">{c.isVerifiedBusiness?<Building2 className="h-5 w-5"/>:c.name.slice(0,1).toUpperCase()}</button><button onClick={()=>setSelected(c)} className="min-w-0 flex-1 text-left"><div className="flex items-center gap-1.5"><span className="truncate text-[15px] font-semibold text-white">{c.name}</span>{c.isVerifiedBusiness&&<ShieldCheck className="h-3.5 w-3.5 text-blue-400"/>}</div><div className="mt-1 truncate text-xs text-slate-500">{c.number}{c.businessCategory?` · ${c.businessCategory}`:''}</div></button><button onClick={()=>onToggleFavorite(c.id)} className="rounded-full p-2 text-slate-600 hover:text-amber-400"><Star className={`h-4 w-4 ${c.isFavorite?'fill-current text-amber-400':''}`}/></button><button onClick={()=>onInitiateCall(c.number,c.name)} className="grid h-10 w-10 place-items-center rounded-full bg-emerald-500/10 text-emerald-400"><Phone className="h-4 w-4 fill-current"/></button></div>)}</div>}
  {selected&&!editing&&!showAdd&&<div className="fixed inset-0 z-[60] flex items-end justify-center bg-black/70 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div className="w-full max-w-md rounded-t-[30px] border border-white/10 bg-[#10161d] p-5 sm:rounded-[30px]"><div className="flex items-start justify-between"><div><div className="grid h-16 w-16 place-items-center rounded-full bg-white/10 text-xl font-bold text-white">{selected.name.slice(0,1).toUpperCase()}</div><h2 className="mt-3 text-xl font-bold text-white">{selected.name}</h2><p className="mt-1 text-sm text-slate-500">{selected.number}</p></div><button onClick={()=>setSelected(null)} className="rounded-full p-2 text-slate-500"><X/></button></div><div className="mt-6 grid grid-cols-3 gap-2"><button onClick={()=>onInitiateCall(selected.number,selected.name)} className="flex flex-col items-center gap-1.5 rounded-2xl bg-emerald-500/10 p-3 text-emerald-400"><Phone className="h-5 w-5"/><span className="text-xs font-semibold">Call</span></button><button onClick={()=>onToggleFavorite(selected.id)} className="flex flex-col items-center gap-1.5 rounded-2xl bg-white/5 p-3 text-amber-400"><Star className="h-5 w-5"/><span className="text-xs font-semibold">Favorite</span></button><button onClick={()=>openEdit(selected)} className="flex flex-col items-center gap-1.5 rounded-2xl bg-white/5 p-3 text-blue-400"><Edit2 className="h-5 w-5"/><span className="text-xs font-semibold">Edit</span></button></div><button onClick={()=>{onDeleteContact(selected.id);setSelected(null)}} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl bg-rose-500/10 p-3 text-sm font-semibold text-rose-400"><Trash2 className="h-4 w-4"/>Delete contact</button></div></div>}
  {(showAdd||editing)&&<div className="fixed inset-0 z-[60] flex items-end justify-center bg-black/70 p-0 backdrop-blur-sm sm:items-center sm:p-4"><form onSubmit={submit} className="w-full max-w-md rounded-t-[30px] border border-white/10 bg-[#10161d] p-5 sm:rounded-[30px]"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs text-slate-500">Contacts</p><h2 className="text-lg font-bold text-white">{editing?'Edit contact':'New contact'}</h2></div><button type="button" onClick={()=>{setShowAdd(false);setEditing(false);setSelected(null)}} className="rounded-full p-2 text-slate-500"><X/></button></div><label className="mb-3 block text-xs font-semibold text-slate-400">Name<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 h-12 w-full rounded-xl border border-white/10 bg-white/5 px-3 text-sm text-white outline-none"/></label><label className="mb-3 block text-xs font-semibold text-slate-400">Phone number<input value={number} onChange={e=>setNumber(e.target.value)} inputMode="tel" className="mt-1 h-12 w-full rounded-xl border border-white/10 bg-white/5 px-3 text-sm text-white outline-none"/></label><label className="mb-5 block text-xs font-semibold text-slate-400">Category<select value={category} onChange={e=>setCategory(e.target.value as ContactItem['category'])} className="mt-1 h-12 w-full rounded-xl border border-white/10 bg-white/5 px-3 text-sm text-white outline-none"><option value="GENERAL">General</option><option value="FAVORITE">Favorite</option><option value="FAMILY">Family</option><option value="WORK">Work</option><option value="BUSINESS">Business</option><option value="PERSONAL">Personal</option></select></label><button type="submit" className="w-full rounded-xl bg-white py-3 text-sm font-bold text-[#0a0f14]">{editing?'Save changes':'Create contact'}</button></form></div>}
 </div>;
}
