import { memo, useEffect, useMemo, useState } from 'react';
import { Check, Clipboard, Delete, Layers, Phone, Search, ShieldAlert, ShieldCheck, User, X } from 'lucide-react';
import { ContactItem, CallLogItem, TruecallerDirectoryProfile, ShieldSettings } from '../types';
import { smartDialerSearch } from '../utils/t9Search';
import { formatPhoneNumber } from '../utils/spamEngine';

interface DialerTabProps { contacts: ContactItem[]; recentCalls: CallLogItem[]; settings: ShieldSettings; lookupProfile: (num: string) => TruecallerDirectoryProfile; onInitiateCall: (number: string, name?: string, sim?: 'SIM 1 (Personal)' | 'SIM 2 (Work)') => void; onOpenCallerDetail: (item: CallLogItem | TruecallerDirectoryProfile) => void; onSaveContact: (number: string, name?: string) => void; selectedSim: 'SIM 1 (Personal)' | 'SIM 2 (Work)'; onChangeSim: (sim: 'SIM 1 (Personal)' | 'SIM 2 (Work)') => void; initialNumber?: string; }
const KEYPAD = [['1',''],['2','ABC'],['3','DEF'],['4','GHI'],['5','JKL'],['6','MNO'],['7','PQRS'],['8','TUV'],['9','WXYZ'],['*',''],['0','+'],['#','']];

const DialerTab = memo(function DialerTab({ contacts, recentCalls, lookupProfile, onInitiateCall, onOpenCallerDetail, selectedSim, onChangeSim, initialNumber }: DialerTabProps) {
 const [value,setValue]=useState(initialNumber||''); const [showSimPicker,setShowSimPicker]=useState(false); const [clipboardNumber,setClipboardNumber]=useState('');
 useEffect(()=>{if(initialNumber)setValue(initialNumber)},[initialNumber]);
 useEffect(()=>{if(value||!navigator.clipboard?.readText)return;navigator.clipboard.readText().then(t=>{const c=t.trim();if(c&&/[\d*#+]/.test(c))setClipboardNumber(c)}).catch(()=>undefined)},[]);
 const pasteNumber=async()=>{try{const t=await navigator.clipboard.readText();if(t.trim()){setValue(t.trim());setClipboardNumber('')}}catch{if(clipboardNumber){setValue(clipboardNumber);setClipboardNumber('')}}};
 const results=useMemo(()=>value.trim()?smartDialerSearch(value,contacts,recentCalls,lookupProfile):{matchingContacts:[],matchingRecents:[],possibleCaller:null},[value,contacts,recentCalls,lookupProfile]);
 const digits=value.replace(/\D/g,''); const matchedContact=useMemo(()=>{if(!digits)return null;return contacts.find(c=>{const n=c.number.replace(/\D/g,'');return n===digits||(digits.length>=7&&n.length>=7&&digits.endsWith(n))})||null},[digits,contacts]);
 const profile=useMemo(()=>digits.length>=4?lookupProfile(value):null,[digits,value,lookupProfile]); const press=(d:string)=>setValue(v=>v+d); const call=()=>{if(value.trim())onInitiateCall(value.trim(),matchedContact?.name||(profile?.isVerified||profile?.isSpam?profile.name:undefined),selectedSim)};
 return <div className="mx-auto w-full max-w-2xl px-4 pb-8 pt-5 sm:px-6">
   <div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-500">Phone</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-white">Keypad</h1></div><button type="button" onClick={()=>setShowSimPicker(true)} className="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3.5 py-2 text-xs font-bold text-slate-200"><Layers className="h-3.5 w-3.5"/>{selectedSim.includes('SIM 1')?'SIM 1':'SIM 2'}</button></div>
   <div className="mx-auto max-w-lg">
    <div className="rounded-[28px] border border-white/10 bg-[#10161d] p-3 shadow-2xl shadow-black/20">
      <div className="flex h-14 items-center rounded-2xl bg-[#080d12] px-4"><Search className="mr-3 h-4 w-4 text-slate-500"/><input id="dialer-search-input" value={value} onChange={e=>{setValue(e.target.value);setClipboardNumber('')}} onKeyDown={e=>{if(e.key==='Enter')call()}} inputMode="tel" autoComplete="off" placeholder="Name or phone number" className="min-w-0 flex-1 bg-transparent text-lg font-medium text-white outline-none placeholder:text-slate-600"/>{!value?<button type="button" onClick={pasteNumber} className="rounded-xl px-2 py-1 text-xs font-bold text-blue-400"><Clipboard className="mr-1 inline h-4 w-4"/>Paste</button>:<button type="button" onClick={()=>setValue('')} className="rounded-full p-2 text-slate-500"><X className="h-4 w-4"/></button>}</div>
      {clipboardNumber&&!value&&<button type="button" onClick={pasteNumber} className="mt-2 flex w-full items-center justify-between rounded-xl bg-blue-500/10 px-3 py-2 text-xs"><span className="text-slate-300">Copied number ready</span><span className="font-bold text-blue-400">Paste</span></button>}
      {(results.matchingContacts.length||results.matchingRecents.length||results.possibleCaller)&&<div className="mt-2 flex gap-2 overflow-x-auto">{results.matchingContacts.slice(0,2).map(c=><button type="button" key={c.id} onClick={()=>setValue(c.number)} className="shrink-0 rounded-xl bg-white/5 px-3 py-2 text-xs font-semibold text-white">{c.name}</button>)}{results.matchingRecents.slice(0,2).map(r=><button type="button" key={r.id} onClick={()=>setValue(r.number)} className="shrink-0 rounded-xl bg-white/5 px-3 py-2 text-xs text-slate-300">{r.callerName||formatPhoneNumber(r.number)}</button>)}{results.possibleCaller&&<button type="button" onClick={()=>onOpenCallerDetail(results.possibleCaller!)} className="flex shrink-0 items-center gap-1 rounded-xl bg-white/5 px-3 py-2 text-xs font-semibold text-white">{results.possibleCaller.isSpam?<ShieldAlert className="h-3.5 w-3.5 text-rose-400"/>:<ShieldCheck className="h-3.5 w-3.5 text-blue-400"/>}{results.possibleCaller.name}</button>}</div>}
    </div>
    <div className="flex min-h-[116px] items-center justify-center px-2 text-center"><div className="min-w-0">{value?<div className="break-all text-[34px] font-light tracking-tight text-white">{formatPhoneNumber(value)}</div>:<div className="text-sm text-slate-600">Enter a number to call</div>}{matchedContact&&<div className="mt-2 flex items-center justify-center gap-1 text-sm font-semibold text-emerald-400"><User className="h-4 w-4"/>{matchedContact.name}</div>}{!matchedContact&&profile?.name&&profile.name!==value&&<div className={`mt-2 text-sm font-medium ${profile.isSpam?'text-rose-400':'text-slate-500'}`}>{profile.name}</div>}</div>{value&&<button type="button" onClick={()=>setValue(v=>v.slice(0,-1))} className="ml-2 rounded-full p-3 text-slate-500 hover:bg-white/5 hover:text-white"><Delete className="h-5 w-5"/></button>}</div>
    <div className="grid grid-cols-3 gap-3 px-5 sm:gap-4">{KEYPAD.map(([digit,letters])=><button type="button" key={digit} onClick={()=>press(digit)} className="mx-auto grid h-[70px] w-[70px] place-items-center rounded-full bg-[#151c24] ring-1 ring-white/5 transition active:scale-95 sm:h-[76px] sm:w-[76px]"><span className="text-[25px] font-medium leading-none text-white">{digit}</span>{letters&&<span className="-mt-1 text-[9px] font-bold tracking-[.2em] text-slate-500">{letters}</span>}</button>)}</div>
    <div className="mt-6 flex justify-center"><button type="button" onClick={call} disabled={!value.trim()} className="grid h-[70px] w-[70px] place-items-center rounded-full bg-emerald-500 text-white shadow-lg shadow-emerald-500/20 transition active:scale-95 disabled:bg-slate-800 disabled:text-slate-600"><Phone className="h-7 w-7 fill-current"/></button></div>
    <div className="mt-7 flex items-center justify-center gap-2 text-[11px] text-slate-600"><ShieldCheck className="h-3.5 w-3.5"/>Calls are protected by VigilShield</div>
   </div>
   {showSimPicker&&<div className="fixed inset-0 z-[60] flex items-end justify-center bg-black/70 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div className="w-full max-w-md rounded-t-[30px] border border-white/10 bg-[#10161d] p-5 sm:rounded-[30px]"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs text-slate-500">Choose line</p><h2 className="text-lg font-bold text-white">Call using</h2></div><button type="button" onClick={()=>setShowSimPicker(false)} className="rounded-full p-2 text-slate-500"><X/></button></div>{(['SIM 1 (Personal)','SIM 2 (Work)'] as const).map(sim=><button type="button" key={sim} onClick={()=>{onChangeSim(sim);setShowSimPicker(false)}} className="mb-2 flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/5 p-4 text-left text-white"><span className="font-semibold">{sim}</span>{selectedSim===sim&&<Check className="h-5 w-5 text-blue-400"/>}</button>)}</div></div>}
 </div>;
});

export default DialerTab;
