import { useState } from 'react';
import { Bell, LockKeyhole, Palette, Settings, ShieldCheck, X } from 'lucide-react';
import ThemeCustomizerModal from './ThemeCustomizerModal';

interface HeaderProps { settings?: any; onToggleShield?:()=>void; isDefaultDialer?:boolean; onRequestDefaultDialer?:()=>void; onOpenPermissionCenter?:()=>void; onSyncDatabase?:()=>void; isSyncing?:boolean; onTriggerIncomingCall?:()=>void; autoCancelEnabled?:boolean; onToggleAutoCancel?:()=>void; onOpenInstallModal?:()=>void; onOpenDataSources?:()=>void; onOpenDiagnostics?:()=>void; }

type Privacy={showCallerDetailsInNotifications:boolean;privacyMode:boolean};
const readPrivacy=():Privacy=>{try{return {...{showCallerDetailsInNotifications:false,privacyMode:true},...JSON.parse(localStorage.getItem('vigilshield_privacy_settings')||'{}')}}catch{return {showCallerDetailsInNotifications:false,privacyMode:true}}};

export default function Header({onOpenPermissionCenter}:HeaderProps){
 const [open,setOpen]=useState(false); const [theme,setTheme]=useState(false); const [privacy,setPrivacy]=useState<Privacy>(readPrivacy);
 const update=(next:Privacy)=>{setPrivacy(next);localStorage.setItem('vigilshield_privacy_settings',JSON.stringify(next));};
 return <>
  <header className="sticky top-0 z-40 border-b border-white/10 bg-[#090e14]/90 backdrop-blur-2xl"><div className="mx-auto flex min-h-[68px] max-w-3xl items-center justify-between gap-3 px-4 sm:px-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-white text-[#0a0f14] shadow-lg"><ShieldCheck className="h-5 w-5"/></div><div><div className="text-[15px] font-bold tracking-tight text-white">VigilShield</div><div className="text-[10px] font-semibold uppercase tracking-[.16em] text-slate-600">Phone & caller protection</div></div></div><div className="flex items-center gap-2"><span className="hidden rounded-full border border-emerald-400/20 bg-emerald-400/10 px-2.5 py-1.5 text-[10px] font-bold text-emerald-400 sm:inline-flex">Protection active</span><button onClick={()=>setOpen(true)} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 bg-white/5 text-slate-400 hover:text-white" aria-label="Settings"><Settings className="h-4 w-4"/></button></div></div></header>
  {open&&<div className="fixed inset-0 z-[70] bg-black/70 backdrop-blur-sm" onMouseDown={()=>setOpen(false)}><section onMouseDown={e=>e.stopPropagation()} className="absolute right-0 top-0 h-full w-full max-w-md overflow-y-auto border-l border-white/10 bg-[#0c1219] shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-white/10 bg-[#0c1219]/95 p-5 backdrop-blur-xl"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-600">Preferences</p><h2 className="mt-1 text-xl font-bold text-white">Settings</h2></div><button onClick={()=>setOpen(false)} className="rounded-full p-2 text-slate-500 hover:bg-white/5"><X className="h-5 w-5"/></button></div><div className="space-y-3 p-4"><button onClick={()=>{setOpen(false);setTheme(true)}} className="flex w-full items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-left"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-500/10 text-blue-400"><Palette className="h-5 w-5"/></span><span className="flex-1"><b className="block text-sm text-white">Appearance</b><span className="mt-1 block text-xs text-slate-500">Theme, accent colour, density and accessibility.</span></span></button><Setting title="Private notifications" description="Keep caller identity minimal on notification and lock screen surfaces." icon={<LockKeyhole className="h-4 w-4"/>} checked={privacy.privacyMode} onChange={v=>update({...privacy,privacyMode:v})}/><Setting title="Detailed caller notifications" description="Allow names and caller risk information in notifications." icon={<Bell className="h-4 w-4"/>} checked={privacy.showCallerDetailsInNotifications} onChange={v=>update({...privacy,showCallerDetailsInNotifications:v})}/>{onOpenPermissionCenter&&<button onClick={()=>{setOpen(false);onOpenPermissionCenter()}} className="w-full rounded-2xl border border-white/10 bg-white/5 p-4 text-left"><b className="block text-sm text-white">Permission Center</b><span className="mt-1 block text-xs text-slate-500">Phone, contacts, call log and notification access.</span></button>}<div className="rounded-2xl border border-white/5 bg-black/10 p-4 text-xs leading-5 text-slate-600">Your call history and contact preferences stay local to the app unless Android permissions are used to sync device data.</div></div></section></div>}
  <ThemeCustomizerModal isOpen={theme} onClose={()=>setTheme(false)}/>
 </>;
}
function Setting({title,description,icon,checked,onChange}:{title:string;description:string;icon:React.ReactNode;checked:boolean;onChange:(v:boolean)=>void}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white/5 text-slate-300">{icon}</span><span className="min-w-0 flex-1"><b className="block text-sm text-white">{title}</b><span className="mt-1 block text-xs leading-5 text-slate-500">{description}</span></span><button role="switch" aria-checked={checked} onClick={()=>onChange(!checked)} className={`relative h-7 w-12 shrink-0 rounded-full ${checked?'bg-blue-500':'bg-slate-700'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${checked?'left-6':'left-1'}`}/></button></div></div>}
