import { useState, useEffect } from 'react';
import { AlertTriangle } from 'lucide-react';
import Header from './components/Header';
import Navigation from './components/Navigation';
import DialerTab from './components/DialerTab';
import RecentsTab from './components/RecentsTab';
import ContactsTab from './components/ContactsTab';
import ProtectionTab from './components/ProtectionTab';
import AssistantTab from './components/AssistantTab';
import IncomingCallOverlay from './components/IncomingCallOverlay';
import ActiveCallModal from './components/ActiveCallModal';
import PostCallModal from './components/PostCallModal';
import CallerDetailModal from './components/CallerDetailModal';
import InstallApkModal from './components/InstallApkModal';
import FastReportModal from './components/FastReportModal';
import DisputeModal from './components/DisputeModal';
import DataSourcesModal from './components/DataSourcesModal';
import SystemDiagnosticsModal from './components/SystemDiagnosticsModal';
import PermissionCenterModal from './components/PermissionCenterModal';
import { BlockRule, WhitelistEntry, ShieldSettings, CallLogItem, IncomingCallState, ActiveCallSession, PostCallState, SecurityTimelineEvent, TruecallerDirectoryProfile, ContactItem, SpamCategory, TabId } from './types';
import { INITIAL_SETTINGS } from './data/defaultData';
import { lookupTruecallerDirectory } from './utils/spamEngine';
import { playCallConnectingTone, playCallCancelledTone } from './utils/audioAlerts';
import { telecomBridge } from './services/telephony/telecomBridge';

export const BASELINE_RULES: BlockRule[] = [{id:'rule-trai-140',value:'140',matchType:'PREFIX',targetType:'BOTH',category:'TELEMARKETING',label:'TRAI Telemarketing Series (140 Series)',notes:'Official Indian telecom regulatory series designated for commercial telemarketing.',enabled:true,hitCount:0,createdAt:Date.now()},{id:'rule-trai-160',value:'160',matchType:'PREFIX',targetType:'BOTH',category:'TELEMARKETING',label:'TRAI Commercial Gateway (160 Series)',notes:'Designated series for commercial call centers and automated notifications.',enabled:true,hitCount:0,createdAt:Date.now()}];
const INITIAL_TIMELINE_EVENTS: SecurityTimelineEvent[] = [];
export default function App(){
 const [activeTab,setActiveTab]=useState<TabId>('dialer'); const [selectedSim,setSelectedSim]=useState<'SIM 1 (Personal)'|'SIM 2 (Work)'>('SIM 1 (Personal)');
 const safeParse=<T,>(key:string,fallback:T):T=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}};
 const [settings,setSettings]=useState<ShieldSettings>(()=>safeParse('vigilshield_settings',INITIAL_SETTINGS)); const [rules,setRules]=useState<BlockRule[]>(()=>safeParse('vigilshield_rules',BASELINE_RULES)); const [whitelist,setWhitelist]=useState<WhitelistEntry[]>(()=>safeParse('vigilshield_whitelist',[])); const [contacts,setContacts]=useState<ContactItem[]>(()=>safeParse('vigilshield_contacts',[])); const [calls,setCalls]=useState<CallLogItem[]>(()=>safeParse('vigilshield_calls',[])); const [timelineEvents,setTimelineEvents]=useState<SecurityTimelineEvent[]>(()=>safeParse('vigilshield_timeline',[]));
 const [autoCancelEnabled,setAutoCancelEnabled]=useState<boolean>(()=>safeParse('vigilshield_autocancel',true));
 const [activeIncomingCall,setActiveIncomingCall]=useState<IncomingCallState|null>(null); const [activeCallSession,setActiveCallSession]=useState<ActiveCallSession|null>(null); const [postCallState,setPostCallState]=useState<PostCallState|null>(null); const [selectedProfile,setSelectedProfile]=useState<TruecallerDirectoryProfile|null>(null); const [selectedCall,setSelectedCall]=useState<CallLogItem|null>(null); const [isCallerModalOpen,setIsCallerModalOpen]=useState(false); const [isInstallModalOpen,setIsInstallModalOpen]=useState(false); const [isFastReportOpen,setIsFastReportOpen]=useState(false); const [fastReportNumber,setFastReportNumber]=useState(''); const [isDisputeOpen,setIsDisputeOpen]=useState(false); const [disputeNumber,setDisputeNumber]=useState(''); const [disputeName,setDisputeName]=useState(''); const [isSyncing,setIsSyncing]=useState(false); const [isDataSourcesModalOpen,setIsDataSourcesModalOpen]=useState(false); const [isDiagnosticsModalOpen,setIsDiagnosticsModalOpen]=useState(false); const [isPermissionCenterOpen,setIsPermissionCenterOpen]=useState(false); const [dialerInitialNumber,setDialerInitialNumber]=useState(''); const [deferredPrompt,setDeferredPrompt]=useState<any>(null); const [isDefaultDialer,setIsDefaultDialer]=useState(()=>telecomBridge.isDefaultDialer());
 useEffect(()=>{const dev=localStorage.getItem('vigilshield_dev_mode')==='true';if(!dev){if(contacts.some(c=>c.id.startsWith('cnt-')||c.name==='Rahul Kumar'||c.name==='Alex Mercer')){setContacts([]);localStorage.removeItem('vigilshield_contacts')}if(calls.some(c=>c.id.startsWith('dev-')||c.id.startsWith('demo-')||c.id.startsWith('call-rec-'))){setCalls([]);localStorage.removeItem('vigilshield_calls')}if(timelineEvents.some(t=>t.id.startsWith('tl-'))){setTimelineEvents([]);localStorage.removeItem('vigilshield_timeline')}}},[]);
 useEffect(()=>telecomBridge.onDialIntent(n=>{setActiveTab('dialer');setDialerInitialNumber(n)}),[]);
 const [toastMessage,setToastMessage]=useState<{text:string,type:'info'|'error'|'success'}|null>(null); const showToast=(text:string,type:'info'|'error'|'success'='info')=>{setToastMessage({text,type});setTimeout(()=>setToastMessage(null),3800)};
 useEffect(()=>{localStorage.setItem('vigilshield_settings',JSON.stringify(settings))},[settings]); useEffect(()=>{localStorage.setItem('vigilshield_rules',JSON.stringify(rules))},[rules]); useEffect(()=>{localStorage.setItem('vigilshield_whitelist',JSON.stringify(whitelist))},[whitelist]); useEffect(()=>{localStorage.setItem('vigilshield_contacts',JSON.stringify(contacts))},[contacts]); useEffect(()=>{localStorage.setItem('vigilshield_calls',JSON.stringify(calls))},[calls]); useEffect(()=>{localStorage.setItem('vigilshield_timeline',JSON.stringify(timelineEvents))},[timelineEvents]); useEffect(()=>{localStorage.setItem('vigilshield_autocancel',JSON.stringify(autoCancelEnabled))},[autoCancelEnabled]);
 const handleSyncDeviceCalls=()=>{if(telecomBridge.isAndroidEnvironment()){try{const d=telecomBridge.fetchDeviceCallLogs(100);if(d?.length){setCalls(d);showToast(`Synchronized ${d.length} call logs from Android device`,'success')}else showToast('No calls found. Check READ_CALL_LOG permission.','info')}catch(e){showToast('Failed to sync device calls','error')}}};
 useEffect(()=>{setIsDefaultDialer(telecomBridge.isDefaultDialer());if(telecomBridge.isAndroidEnvironment()){try{const d=telecomBridge.fetchDeviceCallLogs(100);if(d?.length)setCalls(d);const c=telecomBridge.fetchDeviceContacts(300);if(c?.length)setContacts(c)}catch(e){console.warn('Initial device data sync failed',e)}}const unsub=telecomBridge.subscribe((eventType,payload)=>{const callId=payload?.callId||`call-${Date.now()}`,details=payload?.details,number=details?.number||'',state=details?.state||'RINGING',incoming=details?.isIncoming??(state==='RINGING');if(eventType==='ROLE_STATUS_CHANGED'){setIsDefaultDialer(Boolean(payload?.isDefaultDialer));return}if(eventType==='CALL_ADDED'||eventType==='CALL_STATE_CHANGED'){const p=lookupTruecallerDirectory(number,rules,whitelist);if(incoming&&(state==='RINGING'||state==='CONNECTING'))setActiveIncomingCall({callId,number,callerName:details?.callerDisplayName||p.name||number,carrier:p.carrier||'Cellular',location:p.location||'Incoming Cellular Call',riskScore:p.spamScore,reportsCount:p.spamReportsCount,isSpam:p.isSpam,spamCategory:p.spamCategory,spamReason:p.spamReason,isVerifiedBusiness:p.isVerified,status:'RINGING',countdown:p.isSpam&&autoCancelEnabled?3:0});else if(state==='ACTIVE'||state==='DIALING'||state==='HOLDING'){setActiveIncomingCall(null);setActiveCallSession({id:callId,number,name:details?.callerDisplayName||p.name||number,isSpam:p.isSpam,spamCategory:p.spamCategory,riskScore:p.spamScore,riskLevel:p.riskLevel||'UNKNOWN',durationSeconds:details?.durationSeconds||0,status:state==='HOLDING'?'HELD':'CONNECTED',isMuted:false,isSpeaker:false,isHeld:Boolean(details?.isHolding),isKeypadOpen:false,selectedSim,sim:selectedSim,isVerifiedBusiness:p.isVerified})}}else if(eventType==='CALL_REMOVED'||eventType==='CALL_DISCONNECTED'){setActiveIncomingCall(null);setActiveCallSession(prev=>{if(!prev||callId&&prev.id!==callId)return prev;setPostCallState({isOpen:true,callId:prev.id,number:prev.number,name:prev.name,durationSeconds:prev.durationSeconds||1,durationStr:`${prev.durationSeconds||1}s`,sim:prev.sim,isSpam:prev.isSpam,wasSpam:prev.isSpam});return null});if(telecomBridge.isAndroidEnvironment())try{const fresh=telecomBridge.fetchDeviceCallLogs(100);if(fresh?.length)setCalls(fresh)}catch(e){console.warn(e)}}});return()=>unsub()},[rules,whitelist,selectedSim,autoCancelEnabled]);
 const handleLookupProfile=(n:string)=>lookupTruecallerDirectory(n,rules,whitelist);
 const handleRequestDefaultDialer=()=>telecomBridge.requestDefaultDialerRole();
 const handleSaveNote=(callId:string,note:string)=>{setCalls(prev=>{const target=prev.find(c=>c.id===callId);if(!target)return prev;const key=target.number.replace(/\D/g,'');return prev.map(c=>c.number.replace(/\D/g,'')===key?{...c,notes:note}:c)});showToast(note?'Caller note saved':'Caller note cleared','success')};
 const handleUpdateCallerName=(number:string,newName:string)=>setCalls(prev=>prev.map(c=>c.number.replace(/\D/g,'')===number.replace(/\D/g,'')?{...c,callerName:newName}:c));
 const handleClearAllCalls=()=>{if(window.confirm('Clear your entire call log history?'))setCalls([])};
 const handleInitiateCall=(number:string,name?:string,sim?:'SIM 1 (Personal)'|'SIM 2 (Work)')=>{const clean=number.trim(),digits=clean.replace(/[^\d+*#]/g,''),target=sim||selectedSim,p=lookupTruecallerDirectory(clean,rules,whitelist),matched=contacts.find(c=>c.number.replace(/\D/g,'')===clean.replace(/\D/g,'')),resolved=name||matched?.name||(p.isVerified||p.isSpam?p.name:clean);const result=telecomBridge.placeRealCall(digits,target);if(!result.success){showToast(result.message,'error');return}setActiveCallSession({id:result.callId||`call-${Date.now()}`,number:clean,name:resolved,isSpam:p.isSpam,spamCategory:p.spamCategory,riskScore:p.spamScore,riskLevel:p.riskLevel||'UNKNOWN',durationSeconds:0,status:'DIALING',isMuted:false,isSpeaker:false,isHeld:false,isKeypadOpen:false,selectedSim:target,sim:target,isVerifiedBusiness:p.isVerified});setCalls(prev=>[{id:`call-${Date.now()}`,number:clean,callerName:resolved,type:'OUTGOING',timestamp:Date.now(),durationSeconds:0,isSpam:p.isSpam,spamCategory:p.spamCategory,riskScore:p.spamScore,reportsCount:p.spamReportsCount,carrier:p.carrier,location:p.location,isVerifiedBusiness:p.isVerified,isContact:!!matched},...prev])};
 const handleBlockNumber=(number:string,label:string)=>{const rule={id:`rule-${Date.now()}`,value:number,matchType:'EXACT' as const,targetType:'BOTH' as const,category:'SPAM' as SpamCategory,label:label||`Blocked ${number}`,enabled:true,hitCount:1,createdAt:Date.now()};setRules(p=>[rule,...p]);setCalls(p=>p.map(c=>c.number===number?{...c,isSpam:true,classification:'SPAM' as const,riskLevel:'HIGH_RISK' as const,riskScore:Math.max(c.riskScore,90),spamReason:'Blocked in firewall rules'}:c))};
 const handleWhitelistNumber=(number:string,name:string)=>{setWhitelist(p=>[{id:`wl-${Date.now()}`,value:number,name:name||'Trusted Caller',notes:'Manually verified as safe',createdAt:Date.now()},...p]);setCalls(p=>p.map(c=>c.number===number?{...c,isSpam:false,classification:'SAFE' as const,riskLevel:'SAFE' as const,riskScore:0,userAction:'MARKED_SAFE' as const}:c))};
 return <div className="min-h-screen bg-[#070b10] text-white"><Header/><Navigation activeTab={activeTab} onChangeTab={setActiveTab} spamCallsCount={calls.filter(c=>c.isSpam).length} activeRulesCount={rules.filter(r=>r.enabled).length} assistantAlertsCount={3}/><main className="mx-auto w-full max-w-7xl px-4 py-5 pb-24">{activeTab==='dialer'&&<DialerTab contacts={contacts} recentCalls={calls} settings={settings} lookupProfile={handleLookupProfile} onInitiateCall={handleInitiateCall} onOpenCallerDetail={item=>{const n='number'in item?item.number:'';setSelectedProfile(handleLookupProfile(n));setSelectedCall(calls.find(c=>c.number===n)||null);setIsCallerModalOpen(true)}} onSaveContact={(n,nm)=>handleUpdateCallerName(n,nm)} selectedSim={selectedSim} onChangeSim={setSelectedSim} initialNumber={dialerInitialNumber}/>} {activeTab==='recents'&&<RecentsTab calls={calls} rules={rules} whitelist={whitelist} settings={settings} lookupProfile={handleLookupProfile} onInitiateCall={handleInitiateCall} onSelectCall={call=>{setSelectedProfile(handleLookupProfile(call.number));setSelectedCall(call);setIsCallerModalOpen(true)}} onBlockNumber={handleBlockNumber} onWhitelistNumber={handleWhitelistNumber} onDeleteCall={id=>setCalls(p=>p.filter(c=>c.id!==id))} onClearAllCalls={handleClearAllCalls} onSyncDeviceCalls={handleSyncDeviceCalls}/>} {activeTab==='contacts'&&<ContactsTab contacts={contacts} onInitiateCall={handleInitiateCall} onAddContact={()=>{}} onUpdateContact={()=>{}} onDeleteContact={()=>{}} onToggleFavorite={()=>{}} recentCalls={calls}/>} {activeTab==='protection'&&<ProtectionTab settings={settings} onUpdateSettings={setSettings} rules={rules} onToggleRule={id=>setRules(p=>p.map(r=>r.id===id?{...r,enabled:!r.enabled}:r))} onDeleteRule={id=>setRules(p=>p.filter(r=>r.id!==id))} onAddRule={d=>setRules(p=>[{...d,id:`rule-${Date.now()}`,hitCount:0,createdAt:Date.now()},...p])} whitelist={whitelist} onRemoveWhitelist={id=>setWhitelist(p=>p.filter(w=>w.id!==id))} timelineEvents={timelineEvents}/>} {activeTab==='assistant'&&<AssistantTab calls={calls} contacts={contacts} rules={rules} lookupProfile={handleLookupProfile} onInitiateCall={handleInitiateCall} onAddRule={d=>setRules(p=>[{...d,id:`rule-${Date.now()}`,hitCount:0,createdAt:Date.now()},...p])}/>}</main>
 <CallerDetailModal call={selectedCall} calls={calls} profile={selectedProfile} isOpen={isCallerModalOpen} onClose={()=>setIsCallerModalOpen(false)} onBlockNumber={handleBlockNumber} onMarkSafe={handleWhitelistNumber} onInitiateCall={handleInitiateCall} onOpenReportModal={n=>{setFastReportNumber(n);setIsFastReportOpen(true)}} onOpenDisputeModal={(n,nm)=>{setDisputeNumber(n);setDisputeName(nm);setIsDisputeOpen(true)}} onUpdateCallerName={handleUpdateCallerName} onSaveNote={handleSaveNote}/>
 <IncomingCallOverlay call={activeIncomingCall} autoCancelEnabled={autoCancelEnabled} onCancelCall={(reason)=>{if(activeIncomingCall?.callId)telecomBridge.rejectCall(activeIncomingCall.callId,reason);setActiveIncomingCall(null)}} onAnswerCall={()=>{if(activeIncomingCall?.callId)telecomBridge.answerCall(activeIncomingCall.callId)}} onDismiss={()=>setActiveIncomingCall(null)}/>
 {toastMessage&&<div className="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-2xl border border-slate-700 bg-slate-900 px-4 py-3 text-xs font-semibold shadow-2xl">{toastMessage.text}</div>}
 </div>;
}
